to-do-list/Component/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using ToDoList.Models;
using ToDoList.Repositories;

namespace ToDoList.Component
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private ITasksRepository tasksRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public NavigationMenuViewComponent(ITasksRepository repository, IHttpContextAccessor httpContextAccessor)
        {
            tasksRepository = repository;
            _httpContextAccessor = httpContextAccessor;
        }

        public IViewComponentResult Invoke()
        {
            var projectState = _httpContextAccessor.HttpContext.Session.GetObjectFromJson<ProjectState>("ProjectState");
            if (projectState != null)
            {
                ViewData["ProjectName"] = tasksRepository.GetProject(projectState.ProjectID).ProjectName;
            }
            ViewBag.Username = tasksRepository.GetLoggedInUser();
            List<string> categories = new List<string>();

            if (ViewBag.Type == "Project")
            {
                categories.AddRange(new List<string> { "Active Projects", "Closed Projects" });
            }
            else
            {
                categories.AddRange(new List<string> { "Next", "Backlog", "Completed" });

            }

            return View(categories.Select(x => x).Distinct());
        }
    }
}

to-do-list/Component/TopNavbarViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ToDoList.Models;

namespace ToDoList.Component
{
    public class TopNavbarViewComponent : ViewComponent
    {
        private IHttpContextAccessor _httpContextAccessor;

        public TopNavbarViewComponent(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }
        public IViewComponentResult Invoke()
        {
            var projectState = _httpContextAccessor.HttpContext.Session.GetObjectFromJson<ProjectState>("ProjectState");
            if (projectState != null)
            {
                ViewBag.ProjectID = projectState.ProjectID;
            }
            return View();
        }
    }
}

to-do-list/Controllers/api/DeveloperController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using ToDoList.Models;
using ToDoList.Repositories;

namespace ToDoList.Controllers.api
{
    public class FeedbackResults
    {
        public int MaxPage { get; set; }
        public int? PageNumber { get; set; }
        public string UserSearchValue { get; set; }

        public string DetailsSearchValue { get; set; }
        public List<Suggestion> Feedback { get; set; }
    }

    [ApiController]
    [Route("api/[controller]")]
    public class DeveloperController : ControllerBase
    {
        private IUnitOfWork unitOfWork;

        public DeveloperController(IUnitOfWork _unitOfWork)
        {
            unitOfWork = _unitOfWork;
        }
        [HttpGet]
        public FeedbackResults GetFeedback([FromQuery] int? pageNumber, [FromQuery] string userSearchValue, [FromQuery]string detailsSearchValue)
        {
            var feedbackResults = new FeedbackResults();

            var feedback = unitOfWork.Suggestions.GetAll().OrderByDescending(suggestion => suggestion.SuggestionId).ToList();

            if (!String.IsNullOrEmpty(userSearchValue))
                feedback = feedback.Where(p => p.User.ToLower().Contains(userSearchValue)).ToList();

            if (!String.IsNullOrEmpty(detailsSearchValue))
                feedback = feedback.Where(p => p.Details.ToLower().Contains(detailsSearchValue)).ToList();

            var pageSize = 13;
            var numberOfResults = feedback.Count();
            feedbackResults.MaxPage = (numberOfResults / pageSize) - (numberOfResults % pageSize == 0 ? 1 : 0) + 1;

            if (!pageNumber.HasValue)
                pageNumber = 1;

            feedbackResults.PageNumber = pageNumber;

            feedbackResults.Feedback = feedback.Skip((pageNumber.Value - 1) * pageSize).Take(pageSize).ToList();

            return feedbackResults;
        }
    }
}

to-do-list/Views/Shared/Components/TopNavbar/Default.cshtml
<div id="navbar" class="navbar navbar-inverse bg-inverse" style="overflow:visible;" role="navigation">
    <div class="row">
        <a class="col-2 navbar-brand" asp-controller="Home" asp-action="Index">To-Do Lists</a>
        <div class="navbar-toggler-right">
            <a class="navbar-brand" asp-controller="Home" asp-action="Feedback"><i class="fas fa-smile"></i></a>

            <div class="dropdownDiv">
                <button class="navbar-brand dropbtn"><i class="far fa-user"></i></button>
                <div class="dropdown-list right">
                    @if (ViewBag.ProjectID != null)
                    {
                        <a class="dropdownItem" data-toggle="modal" data-target="#sendInviteModal" href="#">Invite User To Project</a>
                    }
                    <a class="dropdownItem" id="developerHome" asp-controller="Developer" asp-action="Index">Developer Home</a>
                    <a class="dropdownItem" asp-controller="Account" asp-action="Logout">Log Out</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="sendInviteModal" tabindex="-1" role="dialog" aria-labelledby="inviteLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="inviteLabel">Send Invite</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="close">
                    <span aria-hidden="true">x</span>
                </button>
            </div>
            <div class="modal-body">
                <label name="Email">Email:</label>
                <input style="display:inline" id="emailInput" type="email" />
                <button style="display:inline;float:right;" onclick="sendInvite()" type="button" class="btn btn-black">Send Invite</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        if ('@ViewBag.User' == "Developer") {
            $("#developerHome").css("display", "block");
        } else {
            $("#developerHome").css("display", "none");
        }

        sendInvite = function () {
            var userEmail = $("#emailInput").val();
            if (userEmail != "") {
                $.ajax({
                    url: "/Home/SendInvite",
                    dataType: "application/json",
                    data: { userEmail: userEmail }
                });
            }
            $("#emailInput").val("");
        };
    });
</script>